name: testing-deployment
on:
  push:
    branches:
      - deploy

env:
  ACNH_ENV: ${{ }}
jobs:
  build: deploy
    runs-on: ubuntu-latest
    steps:
    # - name: Build front
    #   with: 
    #     REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
    #     REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}
    #   run: npm install
    #   run: npm run build
    # # - name: move front
    # #     run: 
      name: Deploy to Heroku
    - uses: actions/checkout@v2
    - uses: AkhileshNS/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "phone-catalog" #Must be unique in Heroku
        heroku_email: ${{secrets.HEROKU_APP_MAIL}}
        appdir: "phone-back"
        usedocker: true
          docker_build_args: |
            NODE_ENV
            SECRET_KEY
        env:
          NODE_ENV: production
          PORT: ${{ secrets.PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PWD: ${{ secrets.DB_PWD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}

