name: testing-deployment
on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: build react
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - run: cd phone-front && npm ci && npm run build
      - name: move build to backend
        run: cd ..
      - run: mv phone-front/build/* phone-back/public/
      - name: deploy to heroku
        uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phone-catalog" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_APP_MAIL}}
          appdir: "phone-back"
        env:
          NODE_ENV: production
          PORT: ${{ secrets.PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PWD: ${{ secrets.DB_PWD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}

