name: testing-deployment
on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phone-catalog" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_APP_MAIL}}
          appdir: "phone-back"
          env:
            NODE_ENV: production
            PORT: ${{ secrets.PORT }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PWD: ${{ secrets.DB_PWD }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_NAME: ${{ secrets.DB_NAME }}

